name: Report Check-Run
description: "report status of a required check run"

inputs:
  app_id:
    type: string
    description: "GitHub App Id"
  private_key:
    type: string
    description: "GitHub App Private Key"
  id:
    type: string
    description: "name of the check run"

runs:
  using: composite
  steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master

      - name: Generate auth token
        id: generate_token
        uses: ./github/generate-auth-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ inputs.private_key }}

      # https://github.com/LouisBrunner/checks-action
      - name: Report check run
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ steps.generate_token.outputs.token }}
          name: ${{ inputs.id }}
          conclusion: ${{ job.status }}
