name: Checkout Seed Jobs
description: "checkout @daeuniverse/ci-seed-jobs"

checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master
          path: .github/seed-jobs
