name: Instantiate Check-Runs
description: "instantiate required check-runs"

inputs:
  app_id:
    type: string
    description: "GitHub App Id"
  private_key:
    type: string
    description: "GitHub App Private Key"

runs:
  using: composite
  steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master

      - name: Generate auth token
        id: generate_token
        uses: ./github/generate-auth-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ inputs.private_key }}

      # https://github.com/dflydev/check-runs-action
      - name: Prepare Check Runs
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          checks: |
            [
              { "id": "checkout-full-src", "name": "checkout-full-src" },
              { "id": "build-web", "name": "build-web" },
              { "id": "build-bundle", "name": "build-bundle" }
            ]
          status: queued
              # { "id": "checkout-full-src", "name": "dae-bot[bot]/checkout-full-src" },
              # { "id": "build-web", "name": "dae-bot[bot]/build-web" },
              # { "id": "build-bundle", "name": "dae-bot[bot]/build-bundle" },
