---
name: Notify build start
description: Send notification to Telegram channel to notify build has started
# Map input vars to job
inputs:
  workflow_name:
    required: false
  telegram_to:
    required: true
  telegram_token:
    required: true
  git_sha_long:
    required: true
    type: string
  git_sha_short:
    required: true
    type: string
  git_commit_msg:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Send telegram message when build kicks off
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.telegram_to }}
        token: ${{ inputs.telegram_token }}
        format: markdown
        disable_web_page_preview: true
        message: |
          🔨 A new commit: ${{ inputs.git_sha_short }} was pushed to [${{ github.repository }}](https://github.com/${{ github.repository }});

          [${{ inputs.git_sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}): ${{ inputs.git_commit_msg }} by @[${{ github.actor }}](https://http://github.com/${{ github.actor }})

          Workflow: ${{ github.workflow }} has kicked off.
