name: Checkout remote

on:
  workflow_call:
    # Map input vars to job
    inputs:
      repository:
        required: true
        type: string
      head_branch:
        required: true
        type: string

jobs:
  # Pre-Action Stage
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout remote repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.head_branch }}
      - run: |
          echo "hello world!"
