---
name: Post-Build Actions

on:
  workflow_call:
    inputs:
      check-run-id:
        type: string
        description: "name of the check run"
        required: true
      check-run-conclusion:
        type: string
        description: "workflow run status (success|failure|skipped|aborted)"
        required: true

jobs:
  report-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - id: send-notification
        uses: ./common/report-workflow-run@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          id: ${{ inputs.check-run-id }}
          conclusion: ${{ inputs.conclusion }}
