---
name: Post-Build Actions

on:
  workflow_call:
    inputs:
      check-run-id:
        type: string
        description: "name of the check run"
        required: true
      check-run-conclusion:
        type: string
        description: "workflow run status (success|failure|skipped|aborted)"
        required: true

jobs:
  report-workflow-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: daeuniverse/ci-seed-jobs
        ref: master

    - name: Generate auth token
      id: generate_token
      uses: ./github/generate-auth-token
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    # https://github.com/LouisBrunner/checks-action
    - name: Report check run
      uses: LouisBrunner/checks-action@v1.6.1
      if: always()
      with:
        token: ${{ steps.generate_token.outputs.token }}
        name: ${{ inputs.check-run-id }}
        conclusion: ${{ inputs.check-run-conclusion }}
