---
name: Hello World
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@master
      - id: greet
        # uses: daeuniverse/ci-seed-jobs@v1-beta
        uses: ./test/hello-world
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.greet.outputs.random-number }}
        shell: bash
