---
name: Post-Build Actions

on:
  workflow_call:
    inputs:
      check_run_id:
        type: string
        description: "name of the check run"
        required: true
      check_run_conclusion:
        type: string
        description: "workflow run status (success|failure|skipped|aborted)"
        required: true
    secrets:
      app_id:
        required: true
      private_key:
        required: true

jobs:
  report-workflow-run:
    if: ${{ startsWith(github.event.pull_request.head.repo.full_name, github.repository_owner) && inputs.check_run_conclusion != "skipped" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master

      - name: Report workflow run status
        uses: ./common/report-workflow-run
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}
          id: ${{ inputs.check_run_id }}
          conclusion: ${{ inputs.check_run_conclusion }}
