name: Notify build start

on:
  workflow_call:
    # Map input secrets to job
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      git_sha_long:
        description: "git commit sha (long)"
        value: ${{ jobs.export-metadata.outputs.git_sha_long }}
      git_sha_short:
        description: "git commit sha (short)"
        value: ${{ jobs.export-metadata.outputs.git_sha_short }}
      git_commit_msg:
        description: "git commit message"
        value: ${{ jobs.export-metadata.outputs.git_commit_msg }}

jobs:
  # Pre-Action Stage
  export-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Get HEAD git sha
        id: export_commit_sha
        run: |
          echo "git_sha_long=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "git_sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          echo "git_commit_msg=$(git show -s --format=%s)" >> $GITHUB_OUTPUT

    outputs:
      git_sha_long: ${{ steps.export_commit_sha.outputs.git_sha_long }}
      git_sha_short: ${{ steps.export_commit_sha.outputs.git_sha_short }}
      git_commit_msg: ${{ steps.export_commit_sha.outputs.git_commit_msg }}

  notify-build-start:
    needs: [export-metadata]
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🔨 ${{ github.actor }} pushed a new commit: ${{ needs.export-metadata.outputs.git_sha_short }} to [${{ github.repository }}](https://github.com/daeuniverse/container-estate) - [#${{ github.run_number }}](https://github.com/daeuniverse/container-estate/actions/runs/${{ github.run_id }})

            [${{ needs.export-metadata.outputs.git_sha_short }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}): ${{ needs.export-metadata.outputs.git_commit_msg }} by [${{ github.actor }}](https://http://github.com/yqlbu)
