---
name: Post-Build Actions

on:
  workflow_call:
    # Map input secrets to job
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
    # Map input vars to job
    inputs:
      image:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      sha_short:
        required: true
        type: string

jobs:
  notify-build-result:
    if: startsWith(github.event.pull_request.head.repo.full_name, github.repository_owner)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master
      - id: send-notification
        uses: ./notification/notify-build-result
        with:
          telegram_to: ${{ secrets.TELEGRAM_TO }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          image: ${{ inputs.image }}
          image_tag: ${{ inputs.image_tag }}
          sha_short: ${{ inputs.sha_short }}
