---
name: Pre-Build Actions

on:
  workflow_call:
    # Map input secrets to job
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
    # Map input vars to job
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      fetch-depth:
        required: false
        default: 0
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      git_sha_long:
        description: "git sha (long)"
        value: ${{ jobs.export-metadata.outputs.git_sha_long }}
      git_sha_short:
        description: "git sha (short)"
        value: ${{ jobs.export-metadata.outputs.git_sha_short }}
      git_commit_msg:
        description: "git commit message"
        value: ${{ jobs.export-metadata.outputs.git_commit_msg }}

jobs:
  export-metadata:
    runs-on: ubuntu-latest
    outputs:
      git_sha_long: ${{ steps.export.outputs.git_sha_long }}
      git_sha_short: ${{ steps.export.outputs.git_sha_short }}
      git_commit_msg: ${{ steps.export.outputs.git_commit_msg }}
    steps:
      - uses: actions/checkout@master
        with:
          repository: ${{ inputs.repository }}
          fetch-depth: ${{ inputs.fetch-depth }}
          ref: ${{ inputs.ref }}
      - name: Get metadata from HEAD
        id: export
        run: |
          echo "git_sha_long=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          echo "git_sha_short=$(echo ${{ inputs.ref }} | cut -c1-6)" >> $GITHUB_OUTPUT
          echo "git_commit_msg=$(git log --format=%B -n 1 ${{ inputs.ref }})" >> $GITHUB_OUTPUT

  notify-build-start:
    runs-on: ubuntu-latest
    needs: [export-metadata]
    steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master
      - id: send-notification
        uses: ./notification/notify-build-start
        with:
          telegram_to: ${{ secrets.TELEGRAM_TO }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
          git_sha_long: ${{ needs.export-metadata.outputs.git_sha_long }}
          git_sha_short: ${{ needs.export-metadata.outputs.git_sha_short }}
          git_commit_msg: ${{ needs.export-metadata.outputs.git_commit_msg }}
