name: Report Workflow Run Result

on:
  workflow_call:
    inputs:
      id:
        type: string
        description: "name of the check run"
      conclusion::
        type: string
        description: "conclusion of the check run"

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    if: ${{ inputs.source-head }}
    steps:
      - uses: actions/checkout@master
        with:
          repository: daeuniverse/ci-seed-jobs
          ref: master

      - name: Generate auth token
        id: generate_token
        uses: ./github/generate-auth-token
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}

      # https://github.com/LouisBrunner/checks-action
      - name: Report check run
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ steps.generate_token.outputs.token }}
          name: ${{ inputs.id }}
          conclusion: ${{ inputs.conclusion }}
