---
name: Test
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - uses: actions/checkout@master
      - id: send-notification
        uses: ./notification/notify-test
        with:
          msg: "hello"
          telegram_to: ${{ secrets.TELEGRAM_TO }}
          telegram_secret: ${{ secrets.TELEGRAM_SECRET }}
