---
name: Test Report Build Result

on:
  workflow_dispatch:
#     inputs:
#       job_result:
#         required: true
#         type: string
#       checkrun_name:
#         required: true
#         type: string
#       summary:
#         type: string
#         default: ok!
        
jobs:
  generate-auth-token:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/generate-auth-token.yml@master
    secrets: inherit
    
  report-build-result:
    needs: [generate-auth-token]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/dflydev/check-runs-action
      - name: Prepare Check Runs
        uses: dflydev/check-runs-action@v1
        with:
          token: ${{ needs.generate-auth-token.outputs.token }}
          checks: |
            [
              { "id": "phpunit", "name": "PHPUnit" },
              { "id": "psalm", "name": "Psalm" },
              { "id": "phpcs", "name": "PHP_CodeSniffer" },
              { "id": "eslint", "name": "ESLint" },
              { "id": "assets", "name": "npm run production" },
              { "id": "dusk", "name": "Dusk" }
            ]
          status: "queued"
