name: Test check runs

on:
  workflow_dispatch:

jobs:
  instantiate-check-runs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ["checkout-full-src", "build-web", "build-bundle"]
    steps:
      - name: Instantiate required check runs
        uses: daeuniverse/ci-seed-jobs/core/daed/instantiate-check-runs@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          id: "dae-bot[bot]/${{ matrix.id }}"
          
  build:
    needs: [instantiate-check-runs]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: ["checkout-full-src", "build-web", "build-bundle"]
    steps:
      - uses: actions/checkout@master
        id: checkout

      - name: Report result
        uses: daeuniverse/ci-seed-jobs/core/daed/report-check-run@master
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          id: "dae-bot[bot]/${{ matrix.id }}"
